Final_Project/MovieData/Accounts/urls.py
from django.urls import path
from . import views
from . views import *
app_name='Accounts'

urlpatterns = [
    path('registration/',views.registration,name='registration'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('profile/',views.profile,name='profile'),



]

Final_Project/MovieData/MovieData/urls.py
from . import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('MovieApp.urls')),
    path('accounts/',include('Accounts.urls')),
    path('review/',include('RaitingReview.urls')), 
    path('search/',include('search.urls')),   
  
  
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Final_Project/MovieData/RaitingReview/urls.py
from django.urls import path
from . import views
from . views import *

app_name = 'Review'


urlpatterns = [
    path('submit_review/<int:product_id>/', views.submit_review, name='submit_review'),

]

Final_Project/MovieData/search/urls.py
from django.urls import path
from . import views

app_name = 'search'

urlpatterns = [
    path('search_result/',views.search,name='search_result'),
]

Final_Project/MovieData/search/models.py
from django.db import models

# Create your models here.

Final_Project/MovieData/search/views.py
from django.shortcuts import render
from django.db.models import Q
from MovieApp.models import Movies
from django.urls import reverse

# Create your views here.


def search(request):
    movies=None
    query=None
    if 'q' in request.GET:
        query=request.GET.get('q')
        if query:
            movies=Movies.objects.all().filter(Q(movie_tittle__contains=query) | Q(category__movie_category__contains=query))
        return render(request,'search.html',{'query':query,'movies':movies})
    

Final_Project/MovieData/templates/add_movie.html
{% extends "base.html" %}
{% load static %}
{%load crispy_forms_tags %}
{% block body %}
    <form class="form-group" action="{% url 'add_movie' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
         {{ form|crispy }}
         <button type="submit" class="btn btn-primary">Submit</button><br><br>
        </form>
    </form>

       <!-- java script -->
  <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
  <script>
    {% for message in messages %}
      alertify.set('notifier','position', 'top-right');
      alertify.success('{{message}}');
    {% endfor %}
  </script>
{% endblock %}
{% block footer %} 
{% endblock %}

Final_Project/MovieData/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>IMP Super Market</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.3/dist/jquery.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
  <script src="https://kit.fontawesome.com/e0b4029596.js" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<!-- Default theme -->
  <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/themes/default.min.css"/>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<!-- java script -->
  <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>

  <link rel="stylesheet" href="{% static '/css/base.css' %}">
  {% block css %}
  {% endblock %}
  {% block tittle %}
    <title>Base page</title>
  {% endblock %}
  </head>

  <body>
    <!-- navbar -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <!-- <a href=""><img src="{% static 'images/logo-black.png' %}" alt="" style="height: 60px;width: 50px;"></a> -->
        <a class="navbar-brand" href="{% url 'index' %}" style="font-family: monospace;">IMP Records</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Accounts:logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'add_movie'%}">Add movie</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Accounts:profile' %}">
                  <i style='font-size:24px' class='fas'>&#xf406;</i>
                </a>
              </li>
            {% else %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Accounts:registration' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'Accounts:login' %}">Login</a>
              </li>
            {% endif %}
          </ul>
          <form class="d-flex" action="{% url 'search:search_result' %}">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"  name="q">
            <button class="btn btn-outline-success" type="submit" >Search</button>
          </form>
        </div>
      </div>
    </nav><br>
  <!-- end navbar -->

  {% block body %}
    
  {% endblock %}
<br><br><br>

 
<br>

{% block footer%}
<!-- Footer -->
<footer class="section footer-classic context-dark bg-image" style="background: #2d3246;">
  <div class="container">
    <div class="row row-30">
      <div class="col-md-4 col-xl-5">
        <div class="pr-xl-4"><a class="brand" href="index.html"></a>
          <p>We are proving all types of movie deatails.</p>
          <!-- Rights-->
          <p class="rights"><span>©  </span><span class="copyright-year">2018</span><span> </span><span>Waves</span><span>. </span><span>All Rights Reserved.</span></p>
        </div>
      </div>
      <div class="col-md-4">
        <h5>Contacts</h5>
        <dl class="contact-list">
          <dt>Address:</dt>
          <dd>798 South Park Avenue, Jaipur, Raj</dd>
        </dl>
        <dl class="contact-list">
          <dt>email:</dt>
          <dd><a href="mailto:#">aswanthk365@gmail.com</a></dd>
        </dl>
        <dl class="contact-list">
          <dt>phones:</dt>
          <dd><a href="tel:#"></a> <span>or</span> <a href="tel:#">https://karosearch.com</a>
          </dd>
        </dl>
      </div>
      <div class="col-md-4 col-xl-3">
        <h5>Links</h5>
        <ul class="nav-list">
          <li><a href="#">About</a></li>
          <li><a href="{% url 'index' %}">Home</a></li>
        {% if user.is_authenticated %}
          <li><a href="{% url 'add_movie' %}">Add Movies</a></li>
        {% endif %}
          <li><a href="#">Pricing</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="row no-gutters social-container">
    <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-facebook"></span><span>Facebook</span></a></div>
    <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-instagram"></span><span>instagram</span></a></div>
    <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-twitter"></span><span>twitter</span></a></div>
    <div class="col"><a class="social-inner" href="#"><span class="icon mdi mdi-youtube-play"></span><span>google</span></a></div>
  </div>
</footer>
<!-- Footer -->
{% endblock %}
</body>
</html>

Final_Project/MovieData/templates/index.html
{% extends "base.html" %}

{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static '/css/index.css' %}"> 
{% endblock %}
{% block tittle %}
    <title>Home page</title>
{% endblock %}

{% block body %}
{% include 'messages.html' %}
 <div class="movies">
  {% for i in movies.object_list %}
  <div class="card" style="width: 15rem;height: 380px;">
    <a href="{{ i.get_url }}"><img class="card-img-top" src="{{ i.movie_poster.url }}" alt="Card image cap"></a>
    <div class="card-body">
      <h5 class="card-title">
      </h5>
      <p class="card-text">{{ i.movie_tittle }}</p>
      <p class="card-text"style="text-transform: uppercase;">{{ i.category }}</p>
    </div>
  </div>
  {% endfor %}
 </div>
<br><br><br><br><br><br><br>
<!-- paginator -->
<div class="pagination" style="margin-top: 700px;">
  {% if movies.has_next %}
    <a href="?page={{ movies.next_page_number }}">Next</a>
  {% endif %}

  {% for i in movies.paginator.page_range %}
    <a href="?page={{i}}" style="margin-left: 10px;"> {{i}} </a>
  {% endfor %}

  {% if movies.has_previous %}
    <a href="?page={{ movies.previous_page_number }}" style="margin-left: 10px;">Previous</a>
  {% endif %}
</div>


<script>
  setTimeout(function(){
    if ($('#msg').length > 0) {
      $('#msg').remove();
    }
  }, 2000)
</script>
{% endblock %}

Final_Project/MovieData/templates/login.html
{% extends "base.html" %}

{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static '/css/registration.css' %}"> 
{% endblock %}
{% block tittle %}
<title>Login page</title>
{% endblock %}
{% block body %}
{% include 'messages.html' %}

<form class="form-group"method="post">
   {% csrf_token %}
   <label for="username">User name:</label>
   <input type="username" class="form-control" id="username" placeholder="enter username" name="username">
   <label for="pwd">Password:</label>
   <input type="password" class="form-control" id="password" placeholder="Enter password" name="password"><br>
   <button type="submit" onclick="display()" class="btn btn-primary">Submit</button>
</form>

   <!-- java script -->
   <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
   <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script>
   {% endblock %}
   {% block footer %} 
   {% endblock %}

Final_Project/MovieData/templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

Final_Project/MovieData/templates/movie_deatails.html
{% extends "base.html" %}

{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static '/css/movie_deatils.css' %}"> 
{% endblock %}
{% block tittle %}
<title>movie deatail page</title>
{% endblock %}

{% block body %}
{% include 'messages.html' %}
<div class="movie_deatial">
    <div class="img">
        <img src="{{ movie_deatails.movie_poster.url }}" alt="" class="img3" style="height: 1000px;width: 100%;">
        <p>{{ product_deatails.name }}</p>
    </div>
    <div class="details">
         <h1><b>Movie Deatails</b></h1>
         <h3>{{ movie_deatails.movie_tittle }}</h3>
         <h2><b>Discription</b></h2>
         <p>{{ movie_deatails.description }}</p><br><br>
         <h4><b>Movie Trailer</b></h4>
         <p><a href="{{ movie_deatails.movie_trailer}}"<br><br>{{ movie_deatails.movie_trailer}}</a></p>
         <h4><b>Movie Relese At</b></h4>
         <p>{{ movie_deatails.relese_date }}</p><br><br>
         <h4><b>Actors</b></h4>
         <p style="text-transform: uppercase;">{{ movie_deatails.actors }}</p><br><br>
        {% if user.is_authenticated %}
           <a href="{% url 'update_movie' movie_deatails.id %}"><button type="submit" class="btn btn-primary">Update</button></a>   
        {% endif %}
        {% comment %} <a href="{% url 'delete_movie' movie_deatails.id %}">Delete</a> {% endcomment %}

    </div>
</div>



<!-- for review view -->
<h3>Audions Review.............</h3>
<div class="cont">
    {% for i in r %}
    <div class="reviews">
           <article class="box mb-3">
            <div class="icontext w-100">

                <div class="text">
                    <span class="date text-muted float-md-right">{{i.updated_at}} </span>
                    <h6 class="mb-1">{{i.rating}} </h6>
                    <div class="rating-star">
                        <span>
                            <i class="fa fa-star{% if i.rating == 0.5 %}-half-o{% elif review.rating < 1 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if i.rating == 1.5 %}-half-o{% elif review.rating < 2 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if i.rating == 2.5 %}-half-o{% elif review.rating < 3 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if i.rating == 3.5 %}-half-o{% elif review.rating < 4 %}-o {% endif %}" aria-hidden="true"></i>
                            <i class="fa fa-star{% if i.rating == 4.5 %}-half-o{% elif review.rating < 5 %}-o {% endif %}" aria-hidden="true"></i>
                        </span>
                    </div>
                </div>
            </div> <!-- icontext.// -->
            <div class="mt-3">
                <h5>{{i.subject}}</h5>
                <p>
                    {{i.review}}
                </p>
            </div>
        </article>
        
    </div>
    {% endfor %}

</div>

<br><br><br><br>

<!-- add review -->
<form action="{% url 'Review:submit_review' movie_deatails.id %} " method="post">
    {% csrf_token %}
    <h5>Write Your Review</h5>
    <div>
        <!-- Rating stars -->
        <label>How do you rate this movie?</label>
        <br>
        <div class="rate">
            <input type="radio" name="rating" id="rating10" value="5" required /><label for="rating10" title="5"></label>
            <input type="radio" name="rating" id="rating9" value="4.5" required /><label for="rating9" title="4.5" class="half"></label>
            <input type="radio" name="rating" id="rating8" value="4" required /><label for="rating8" title="4"></label>
            <input type="radio" name="rating" id="rating7" value="3.5" required /><label for="rating7" title="3.5" class="half"></label>
            <input type="radio" name="rating" id="rating6" value="3" required /><label for="rating6" title="3"></label>
            <input type="radio" name="rating" id="rating5" value="2.5" required /><label for="rating5" title="2.5" class="half"></label>
            <input type="radio" name="rating" id="rating4" value="2" required /><label for="rating4" title="2"></label>
            <input type="radio" name="rating" id="rating3" value="1.5" required /><label for="rating3" title="1.5" class="half"></label>
            <input type="radio" name="rating" id="rating2" value="1" required /><label for="rating2" title="1"></label>
            <input type="radio" name="rating" id="rating1" value="0.5" required /><label for="rating1" title="0.5" class="half"></label>
        </div>
<br>
        Review Title:
        <input type="text" class="form-control" name="subject">
        <br>
        Review:
        <textarea name="review" rows="4" class="form-control"></textarea>
        <br>
        {% if user.is_authenticated %}
            <input type="submit" value="Submit Review" class="btn btn-primary">
        {% else %}
            <p>You must be logged in to post a review. <span><a href="{% url 'Accounts:login' %}">Login now</a></span></p>
        {% endif %}

    </div>
</form>
<script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script>
{% endblock %}

Final_Project/MovieData/templates/profile.html
{% extends "base.html" %}
{% load static %}
{%load crispy_forms_tags %}
{% block tittle %}
  <title>Profile page</title>
{% endblock %}
{% block body %}

{% include 'messages.html' %}


<div class="container col-md-6 table-bordered rounded">
  <div class="content-section">
    <div class="media">
      <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
      <div class="media-body">
        <h2 class="account-heading">{{ user.username }}</h2>
        <p class="text-secondary">{{ user.email }}</p>
      </div>
    </div>

  <!-- Don't Forget To Add enctype="multipart/form-data". If We Leave This, Then It Won't Save Data In The Background -->
   <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <fieldset class="form-group">
              <legend class="border-bottom mb-4">Profile Info</legend>      
              {{ u_form|crispy }}
              {{ p_form|crispy }}
          </fieldset>
          <div class="form-group">
              <button class="btn btn-outline-info" type="submit">Update</button>
          </div>
      </form> 
   </div>
</div>

  <img src="{{ user.Profile.image.url }}" class="img-fluid">


  <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script>

{% endblock %}

Final_Project/MovieData/templates/registration.html
{% extends "base.html" %}

{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static '/css/registration.css' %}"> 
{% endblock %}
{% block tittle %}
<title>Registration page</title>
{% endblock %} 

{% block body %}
{% include 'messages.html' %}

<div>
  <h1><b><center>Registration Form</center></b></h1>
<div class="container">
  <form class="form-group" action="{% url 'Accounts:registration' %}" method="post">
   {% csrf_token %}

    <label for="username">User name:</label>
    <input type="username" class="form-control" id="username" placeholder="enter username" name="username">
    
    <label for="first_name">First Name:</label>
    <input type="first_name" class="form-control" id="first_name" placeholder="Enter first_name" name="first_name">

    <label for="last_name">Last name:</label>
    <input type="last_name" class="form-control" id="last_name" placeholder="Enter last_name" name="last_name">
    

    <label for="email">Email:</label>
    <input type="email" class="form-control" id="email" placeholder="Enter email" name="email">
    
    <label for="pwd">Password:</label>
    <input type="password" class="form-control" id="password" placeholder="Enter password" name="password">
    
    <label for="pwd">Password:</label>
    <input type="password1" class="form-control" id="password1" placeholder="Enter password" name="password1"><br>
    
    <button type="submit" class="btn btn-primary">Submit</button><br><br>
    <p>I have already have an account <a href="{% url 'Accounts:login'%}">Click here</p></a>
  </form>
</div>

</div>
<div>

   <!-- java script -->
  <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
  <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script>
{% endblock %}
{% block footer %} 
{% endblock %}

Final_Project/MovieData/templates/search.html
{% extends "base.html" %}
{% load static %}

{% block css %} 
    <link rel="stylesheet" href="{% static '/css/index.css' %}"> 
{% endblock %}

{% block body %}
<h2><b>You search for </b> '{{query}}'</h2>
 <div class="products">
  {% for i in movies %}
  <div class="card" style="width: 15rem;height: 380px;">
    <a href="{{ i.get_url }}"><img class="card-img-top" src="{{ i.movie_poster.url }}" alt="Card image cap"></a>
    <div class="card-body">
      <h5 class="card-title">
      </h5>
      <p class="card-text">{{ i.movie_tittle }}</p>
      <p class="card-text">{{ i.movie_tittle }}</p>
    </div>
  </div>
 </div>
{% empty %}
    <h3 style="color: white;"><b> No result found.........</b></h3>
{% endfor %}<br>

{% endblock %}

{% block footer %} 
{% endblock %}

Final_Project/MovieData/templates/update.html
{% extends "base.html" %}
{% load static %}
{%load crispy_forms_tags %}

{% block tittle %}
<title>Movie Update page</title>
{% endblock %}

{% block body %}
{% include 'messages.html' %}

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}

        {{form|crispy }}
        <button type="submit" class="btn btn-primary">Submit</button><br><br>
      </form>
<!-- java script -->
  <script src="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/alertify.min.js"></script>
  <script>
    setTimeout(function(){
      if ($('#msg').length > 0) {
        $('#msg').remove();
      }
    }, 2000)
  </script>
{% endblock %}
{% block footer %} 
{% endblock %}